services:
  mongodb:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  auth-service:
    build:
      context: ./services/auth-service
    environment:
      PORT: 4001
      MONGODB_URI: mongodb://mongodb:27017/unified-ott
      JWT_ACCESS_SECRET: access-secret-key
      JWT_REFRESH_SECRET: refresh-secret-key
      CORS_ORIGIN: http://localhost:3000
      ANALYTICS_SERVICE_URL: http://analytics-service:4004
      INTERNAL_API_SECRET: internal-secret-key
      ADMIN_API_SECRET: admin-secret-key
      PAYMENTS_WEBHOOK_SECRET: payments-secret-key
    ports:
      - "4001:4001"
    depends_on:
      - mongodb
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
  api-gateway:
    build:
      context: ./services/api-gateway
    environment:
      PORT: 4000
      AUTH_SERVICE_URL: http://auth-service:4001
      CONTENT_SERVICE_URL: http://content-service:4002
      PAYMENTS_SERVICE_URL: http://payments-service:4003
      ANALYTICS_SERVICE_URL: http://analytics-service:4004
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "4000:4000"
    depends_on:
      - auth-service
      - content-service
      - payments-service
      - analytics-service
  content-service:
    build:
      context: ./services/content-service
    environment:
      PORT: 4002
      MONGODB_URI: mongodb://mongodb:27017/unified-ott
      CORS_ORIGIN: http://localhost:3000
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ANALYTICS_SERVICE_URL: http://analytics-service:4004
      DOWNLOAD_SIGNING_SECRET: download-signing-secret
    ports:
      - "4002:4002"
    depends_on:
      - mongodb
      - elasticsearch
  payments-service:
    build:
      context: ./services/payments-service
    environment:
      PORT: 4003
      AUTH_SERVICE_URL: http://auth-service:4001
      PAYMENTS_WEBHOOK_SECRET: payments-secret-key
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "4003:4003"
    depends_on:
      - auth-service
  analytics-service:
    build:
      context: ./services/analytics-service
    environment:
      PORT: 4004
      MONGODB_URI: mongodb://mongodb:27017/unified-ott
      CORS_ORIGIN: http://localhost:3000
      AUTH_SERVICE_URL: http://auth-service:4001
      INTERNAL_API_SECRET: internal-secret-key
    ports:
      - "4004:4004"
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./apps/frontend
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:4000
      API_BASE_URL: http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway

volumes:
  mongo_data:
